version: "3.1"

services:
  valheim_server:
    build: .
    image: valheim
    restart: unless-stopped
    environment:
      - WORLD_NAME=${COMPOSE_PROJECT_NAME}
      - WORLD_PASSWORD=${WORLD_PASSWORD}
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - ${PORT_RANGE}:2456-2458/udp
    volumes:
      - ./worlds/${COMPOSE_PROJECT_NAME}:/valheim/worlds_local
